site:
    title: Ersel's Blog
    tagline: Tech, Business, Books and everything else...
posts:
    -
        title: "Artificial Intelligence: Key to the future or Pandora's box - part 1"
        filename: artificial-intelligence-essay-part1.html
        date: 2016-07-07
        template: post.html
        content: ai-essay-p1.md
        category: essays
    -
        title: "Artificial Intelligence: Race between humans and the machines - part 2"
        filename: artificial-intelligence-essay-part2.html
        date: 2017-03-25
        template: post.html
        content: ai-essay-p2.md
        category: essays
    -
        title: "Software Projects"
        filename: software-projects.html
        date: 2017-06-10
        template: post.html
        content: projects.md
        category: projects
